parameters:
    gc_security.authentication_handler: GC\UserBundle\AuthenticationHandler

services:
    authentication_handler:
        class:  %gc_security.authentication_handler%
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger' channel: 'security' }
    gc_user.gc_provider:
            class: GC\UserBundle\Security\GCUserProvider
            public: false
            arguments: ["@fos_user.user_manager"]