parameters:
    gc_security.authentication_handler: GC\UserBundle\AuthenticationHandler

services:
    authentication_handler:
        class:  %gc_security.authentication_handler%
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger' channel: 'security' }