<?php

namespace GC\DataLayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function getCategories() {
        $result = $this->_em->createQuery('SELECT c FROM GC\DataLayerBundle\Entity\Category c where c.lft > 1 AND c.rgt < (SELECT x.rgt FROM GC\DataLayerBundle\Entity\Category x WHERE x.parentId IS NULL)')->getResult();
        return $result;
    }

    public function getSubtree($name) {
        return $this->_em->createQuery('SELECT c FROM GC\DataLayerBundle\Entity\Category c where c.lft > (SELECT x.lft FROM GC\DataLayerBundle\Entity\Category x WHERE x.name=:name) AND c.rgt < (SELECT y.rgt FROM GC\DataLayerBundle\Entity\Category y WHERE y.name=:name) ORDER BY c.lft')
        	->setParameter("name", $name)
        	->getResult();
        
    }	
}