<?php

namespace GC\DataLayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    public function getGrooveCount($project) {
        return  $this->_em->createQuery('SELECT COUNT(g.id) FROM GC\DataLayerBundle\Entity\Groove g 
        	JOIN g.grooveSet gs WHERE gs.project = :project')
        ->setParameter('project', $project)
        ->getSingleScalarResult();
    }


}