<?php

namespace GC\DataLayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    public function createIfNotExists($name) {
        $tag_count = $this->_em->createQuery('SELECT COUNT(t.id) FROM GC\DataLayerBundle\Entity\Tag t WHERE t.name = :tag')
                ->setParameter('tag', $name)
                ->getSingleScalarResult();

        if ($tag_count > 0) {
            return $this->findOneByName($name);
        } else {
            $tag = new Tag();
            $tag->setName($name);
            $tag->setCount(0);
            $this->_em->persist($tag);
            $this->_em->flush();
            return $tag;            
        }
    }

    public function linkTag($project, $tagName) {
        if($project->hasTag($tagName)) {
            return 0;
        } else {
            $tag = $this->createIfNotExists($tagName);  
            $project->addTag($tag);
            $this->_em->persist($project);
            return 1;
        }
    }
}