<?php

namespace GC\DataLayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findAllActiveProjects($user) {
	    $query = $this->getEntityManager()
	        ->createQuery('
	            SELECT p, u FROM GCDataLayerBundle:Project p
	            JOIN p.user u
	            WHERE p.user = :user
	            AND p.enabled=1
	            AND p.expiresAt > :now'
	        )->setParameter('user', $user)
	        ->setParameter('now', new \DateTime('now'));

	    try {
	        return $query->getResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}