parameters:
#    gc_welcome.example.class: GC\WelcomeBundle\Example

services:
#    gc_welcome.example:
#        class: %gc_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
