imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: @GCDataLayerBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

#Services:
services:
    gc.twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: 'twig.extension' }

#Amazon Web Services
cybernox_amazon_web_services:
    key:    %aws_key%
    secret: %aws_secret%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: GC\DataLayerBundle\Entity\User
    use_listener: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        user_image_path: /img/profiles/

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: /usr/bin/java
    filters:
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
        cssrewrite: ~        
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        unix_socket: %database_socket%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        # entity_managers:
        #     default:
        #         mappings:
        #             FOSUserBundle:
        #                 type: xml
        #                 dir: Resources/config/doctrine
        #             GCGrooveBundle:
        #                 type: yml
        #                 dir: Resources/config/doctrine/metadata/orm
        #             GCProjectBundle:
        #                 type: yml
        #                 dir: Resources/config/doctrine/metadata/orm
        #             GCUserBundle:
        #                 type: yml
        #                 dir: Resources/config/doctrine/metadata/orm

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
