GCDashboardBundle:
    resource: "@GCDashboardBundle/Resources/config/routing.yml"
    prefix:   /

GCDataLayerBundle:
    resource: "@GCDataLayerBundle/Resources/config/routing.yml"
    prefix:   /

GCUserBundle:
    resource: "@GCUserBundle/Resources/config/routing.yml"
    prefix:   /

GCWelcomeBundle:
    resource: "@GCWelcomeBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
