GrooveType:
  type: entity
  table: groove_type
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 60
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
