Message:
  type: entity
  table: message
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    body:
      type: text
      nullable: false
    subject:
      type: string
      length: 255
      fixed: false
      nullable: true
    createAt:
      type: datetime
      nullable: false
      column: create_at
  oneToOne:
    toUser:
      targetEntity: FosUser
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        to_user_id:
          referencedColumnName: id
      orphanRemoval: false
    fromUser:
      targetEntity: FosUser
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        from_user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
