_categorylist:
    pattern:  categories/
    defaults: { _controller: GCProjectBundle:Category:index }

_categoryadd:
    pattern:  categories/add
    defaults: { _controller: GCProjectBundle:Category:add }
