parameters:
#    gc_project.example.class: GC\ProjectBundle\Example

services:
#    gc_project.example:
#        class: %gc_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
