AssetType:
  type: entity
  table: asset_type
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      nullable: false
      unique: true;
  lifecycleCallbacks: {  }
