ProjectTag:
  type: entity
  table: project_tag
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
  oneToOne:
    tag:
      targetEntity: Tag
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        tag_id:
          referencedColumnName: id
      orphanRemoval: false
    project:
      targetEntity: Project
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        project_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
