Tag:
  type: entity
  table: tag
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 40
      fixed: false
      nullable: false
    count:
      type: integer
      unsigned: false
      nullable: false
  lifecycleCallbacks: {  }
