WatchCategory:
  type: entity
  table: watch_category
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
  oneToOne:
    category:
      targetEntity: Category
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        category_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: User
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
