GrooveSetComment:
  type: entity
  table: groove_set_comment
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    body:
      type: text
      nullable: true
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    modifiedAt:
      type: datetime
      nullable: true
      column: modified_at
  oneToOne:
    grooveSet:
      targetEntity: GrooveSet
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        groove_set_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: User
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
