GrooveSet:
  type: entity
  table: groove_set
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    description:
      type: text
      nullable: true
    rating:
      type: smallint
      nullable: true
    privateComments:
      type: integer
      unsigned: false
      nullable: false
      column: private_comments
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    modifiedAt:
      type: datetime
      nullable: true
      column: modified_at
  oneToOne:
    project:
      targetEntity: Project
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        project_id:
          referencedColumnName: id
      orphanRemoval: false
    user:
      targetEntity: User
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
